{
  "cve_id": "CVE-2020-22916",
  "timestamp": "2025-01-14 16:58:34",
  "phases": {
    "primary": {
      "completed": true,
      "timestamp": "2025-01-10 10:39:54"
    },
    "secondary": {
      "completed": true,
      "timestamp": "2025-01-11 20:55:24"
    },
    "extraction": {
      "completed": true,
      "timestamp": "2025-01-12 03:38:12"
    }
  },
  "urls": [
    {
      "url": "http://web.archive.org/web/20230918084612/https://github.com/snappyJack/CVE-request-XZ-5.2.5-has-denial-of-service-vulnerability",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2234987",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://bugzilla.suse.com/show_bug.cgi?id=1214590",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://github.com/snappyJack/CVE-request-XZ-5.2.5-has-denial-of-service-vulnerability",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://github.com/tukaani-project/xz/issues/61",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://security-tracker.debian.org/tracker/CVE-2020-22916",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://tukaani.org/xz/",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    }
  ]
}