{
  "cve_id": "CVE-2022-25133",
  "timestamp": "2025-01-14 00:42:51",
  "phases": {
    "primary": {
      "completed": true,
      "timestamp": "2025-01-08 10:43:25"
    },
    "secondary": {
      "completed": false,
      "timestamp": null
    },
    "extraction": {
      "completed": false,
      "timestamp": null
    }
  },
  "urls": [
    {
      "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/220084",
      "status": "unknown",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://github.com/pjqwudi1/my_vuln/blob/main/totolink/vuln_20/20.md",
      "status": "failed",
      "reason": "Failed to fetch content",
      "timestamp": "2025-01-09 18:08:56"
    }
  ]
}