{
  "cve_id": "CVE-2024-21520",
  "timestamp": "2025-01-14 00:42:31",
  "phases": {
    "primary": {
      "completed": true,
      "timestamp": "2025-01-10 10:40:11"
    },
    "secondary": {
      "completed": true,
      "timestamp": "2025-01-11 20:55:53"
    },
    "extraction": {
      "completed": true,
      "timestamp": "2025-01-13 04:47:51"
    }
  },
  "urls": [
    {
      "url": "https://github.com/encode/django-rest-framework/commit/3b41f0124194430da957b119712978fa2266b642",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://github.com/encode/django-rest-framework/compare/3.15.1...3.15.2",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://github.com/encode/django-rest-framework/pull/9435",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-DJANGORESTFRAMEWORK-7252137",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    }
  ]
}