{
  "cve_id": "CVE-2022-34310",
  "timestamp": "2025-01-14 00:42:28",
  "phases": {
    "primary": {
      "completed": true,
      "timestamp": "2025-01-10 10:40:00"
    },
    "secondary": {
      "completed": true,
      "timestamp": "2025-01-11 20:55:49"
    },
    "extraction": {
      "completed": true,
      "timestamp": "2025-01-13 00:59:12"
    }
  },
  "urls": [
    {
      "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/229441",
      "status": "unknown",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://www.ibm.com/support/pages/node/6832922",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://www.ibm.com/support/pages/node/6832924",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    }
  ]
}