{
  "cve_id": "CVE-2023-45167",
  "timestamp": "2025-01-14 00:42:24",
  "phases": {
    "primary": {
      "completed": true,
      "timestamp": "2025-01-10 10:39:58"
    },
    "secondary": {
      "completed": true,
      "timestamp": "2025-01-11 20:55:44"
    },
    "extraction": {
      "completed": true,
      "timestamp": "2025-01-12 20:47:04"
    }
  },
  "urls": [
    {
      "url": "https://aix.software.ibm.com/aix/efixes/security/python_advisory6.asc",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/267965",
      "status": "unknown",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://www.ibm.com/support/pages/node/7068084",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    }
  ]
}