

[Mailman 3 python.org](/archives/)

[Sign In](/accounts/login/?next=/archives/list/security-announce%40python.org/thread/BMAK5BCGKYWNJOACVUSLUF6SFGBIM4VP/)
[Sign Up](/accounts/signup/?next=/archives/list/security-announce%40python.org/thread/BMAK5BCGKYWNJOACVUSLUF6SFGBIM4VP/)

[Manage this list](/mailman3/lists/security-announce.python.org/)
[Sign In](/accounts/login/?next=/archives/list/security-announce%40python.org/thread/BMAK5BCGKYWNJOACVUSLUF6SFGBIM4VP/)
[Sign Up](/accounts/signup/?next=/archives/list/security-announce%40python.org/thread/BMAK5BCGKYWNJOACVUSLUF6SFGBIM4VP/)

×
#### Keyboard Shortcuts

### Thread View

* `j`: Next unread message
* `k`: Previous unread message
* `j a`: Jump to all threads* `j l`: Jump to MailingList overview

[newer](/archives/list/security-announce%40python.org/thread/PLP2JI3PJY33YG6P5BZYSSNU66HASXBQ/ "[CVE-2024-5642] Buffer over-read in SSLContext.set_npn_protocols() for Python 3.9 and earlier")

[[CVE-2024-5642] Buffer over-read...](/archives/list/security-announce%40python.org/thread/PLP2JI3PJY33YG6P5BZYSSNU66HASXBQ/ "[CVE-2024-5642] Buffer over-read in SSLContext.set_npn_protocols() for Python 3.9 and earlier")

### [CVE-2024-0397] Memory race condition in ssl.SSLContext certificate store methods

[older](/archives/list/security-announce%40python.org/thread/NRUHDUS2IV2USIZM2CVMSFL6SCKU3RZA/ "[CVE-2024-4032] Incorrect IPv4 and IPv6 private ranges")

[[CVE-2024-4032] Incorrect IPv4 and...](/archives/list/security-announce%40python.org/thread/NRUHDUS2IV2USIZM2CVMSFL6SCKU3RZA/ "[CVE-2024-4032] Incorrect IPv4 and IPv6 private ranges")

![](https://secure.gravatar.com/avatar/b5a0900288ad3a29fd4a5ef260486055.jpg?s=120&d=mm&r=g)

## [Seth Larson](/archives/users/eb0c073014124400ac984fd5e76d1f7e/ "See the profile for Seth Larson")

17 Jun
2024

17 Jun
'24

2:02 p.m.

A defect was discovered in the Python “ssl” module where there is a memory
race condition with the ssl.SSLContext methods “cert\_store\_stats()” and
“get\_ca\_certs()”. The race condition can be triggered if the methods are
called at the same time as certificates are loaded into the SSLContext,
such as during the TLS handshake with a certificate directory configured.
This issue is fixed in CPython 3.10.14, 3.11.9, 3.12.3, and 3.13.0a5.

Severity: Low

References

* <https://github.com/python/cpython/issues/114572>
* <https://github.com/python/cpython/pull/114573>

Attachments:

* [attachment.html](/archives/list/security-announce%40python.org/message/BMAK5BCGKYWNJOACVUSLUF6SFGBIM4VP/attachment/2/attachment.html)
  (text/html — 779 bytes)

[0](#like "You must be logged-in to vote.")
[0](#dislike "You must be logged-in to vote.")

Reply

[Sign in to reply online](/accounts/login/?next=/archives/list/security-announce%40python.org/thread/BMAK5BCGKYWNJOACVUSLUF6SFGBIM4VP/)
Use email software

[Show replies by date](/archives/list/security-announce%40python.org/thread/BMAK5BCGKYWNJOACVUSLUF6SFGBIM4VP/?sort=date)

![Loading...](/static/hyperkitty/img/ajax-loader.gif)
[Visit here for a non-javascript version of this page.](/archives/list/security-announce%40python.org/thread/BMAK5BCGKYWNJOACVUSLUF6SFGBIM4VP/?noscript)

208
Age (days ago)

208
Last active (days ago)

[List overview](/archives/list/security-announce%40python.org/)

[Download](/archives/list/security-announce%40python.org/export/security-announce%40python.org-BMAK5BCGKYWNJOACVUSLUF6SFGBIM4VP.mbox.gz?thread=BMAK5BCGKYWNJOACVUSLUF6SFGBIM4VP "This thread in gzipped mbox format")

0 comments

1 participants

[Add to favorites](#AddFav "You must be logged-in to have favorites.")
[Remove from favorites](#RmFav)

### tags

### participants (1)

* ![](https://secure.gravatar.com/avatar/b5a0900288ad3a29fd4a5ef260486055.jpg?s=48&d=mm&r=g)
  Seth Larson

![HyperKitty](/static/hyperkitty/img/logo.png)
Powered by [HyperKitty](http://hyperkitty.readthedocs.org) version 1.3.12.

